### ISSUE TITLE
What is reasoning on note ordering?

### ISSUE THREAD

**Issue by CptanPanic** [git-moss/APCmini4Bitwig#2]
Thanks for making plugin, and it works great for me, but I am still getting used to the note order when in note mode.  For example the first row is an octave, and then next row starts a 4th up from the first note on bottom row?  I was just wondering why you didn't just make it continue from top note on bottom row, or at least double the root and have each row start on root?

**Comment by git-moss** [comment]
This was copied from Abletons Push. It allows to play chords with the same patterns in all scales. E.g. look here: https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-frc3/1399617_695523497127218_1949592757_o.jpg

**Comment by CptanPanic** [comment]
Thanks.
