### ISSUE TITLE
Fader positions are read from Script and update Tracks without asking.

### ISSUE THREAD

**Issue by cellrok** [git-moss/APCmini4Bitwig#4]
I noticed that sometimes the phsysical fader positions are read into Bitwig without touching them at random intervals (or after certain actions, cleanup task?). 

This is a problem because the faders may be not in sync with the current project. 

Example: i load a project with Track 1 at -6db and the related fader on APC is still at -2db from the last session.. After 15 minutes or so the value from the controller is read into the session sets the volume from Track 1 to -2db without asking, making it suddenly louder.. 

This behavior stops if i use the fader at least once on all tracks and set it to some value close  to what the project initally was. I think this is wrong. The script shouldn't just try to force the fader positions to match. If i don't use them, they should do nothing.

**Comment by git-moss** [comment]
See issue #3.
