### ISSUE TITLE
Compatibility issues with Push4Bitwig

### ISSUE THREAD

**Issue by cellrok** [git-moss/APCmini4Bitwig#5]
When running APC Mini and Push at the same time one of them starts to hang after a couple minutes. Usually it is the Push. I have to turn the Push off and unplug the APC to get the Push working again. 

Not sure how Bitwig scripting host treats multiple controller scripts, but it looks like they communicate in some way and mess eachother up.

PS: i am not trying to use the "push features" on the APC or something. I just wanted to use the APC as clip launcher in session view, while i play notes on my Push.

**Comment by git-moss** [comment]
See issue #3.
