### ISSUE TITLE
Is it possible to select chromatic scale for the note sequencer?

### ISSUE THREAD

**Issue by actionless** [git-moss/APCmini4Bitwig#6]
In this video with the bigger controller (https://www.youtube.com/watch?v=4Ul2Z3zsNrc) it was shown what that scale is presented.
However here (https://github.com/git-moss/APCmini4Bitwig/wiki#note-sequencer) there is no any reference about chromatic scale.
And I can't get what actually is being affected by switching "In key" option in preferences (https://github.com/git-moss/APCmini4Bitwig/wiki#preferences-dialog) between "In key" and "Chromatic"

**Comment by git-moss** [comment]
Thanks for reporting! Setting scale layout and chromatic mode was broken. I also updated the Wiki documentation.
Checkout the new version on GitHub.

**Comment by actionless** [comment]
atm i worked around that with:
```diff
+++ framework/helper/Scales.js  2016-02-04 17:56:22.380618734 +0100
@@ -38,6 +38,7 @@

 Scales.INTERVALS =
 [
+    { name: 'Chromatic',        notes: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ] },
     { name: 'Major',            notes: [ 0, 2, 4, 5, 7,  9,  11 ] },
     { name: 'Minor',            notes: [ 0, 2, 3, 5, 7,  8,  10 ] },
     { name: 'Dorian',           notes: [ 0, 2, 3, 5, 7,  9,  10 ] },
``` 
but it's not very handy

what do you think about binding Scales.setChromatic to the bottom right button of shift menu (right after the "piano keyboard" tone selector)?

**Comment by git-moss** [comment]
What's wrong with the current implementation? Have your read my answer above?

**Comment by actionless** [comment]
if i understood current it's possible now to switch it only from setting dialog, right? or it's binded to some key on the controller?

**Comment by git-moss** [comment]
It is the 6th key. See the updated Wiki documentation for Play Mode.

**Comment by actionless** [comment]
my bad, was cheking only Changelog wiki page
