### ISSUE TITLE
Navigation buttons work incorrectly

### ISSUE THREAD

**Issue by askaliuk** [git-moss/APCmini4Bitwig#7]
Current `master` (as of Sep 23, 2016) has following issue:
 * `shift + up arrow` works like `shift + left arrow` button (and vise versa)
 * `shift + down arrow` works like `shift + right arrow` button (and vise versa)

Bitwig 1.3.9

**Comment by git-moss** [comment]
Please ellaborate a bit more: In what mode do you have a problem and what is different to what you expect?

**Comment by askaliuk** [comment]
Sure.
APC Mini has 4 buttons for session navigation: `shift + left arrow`, `shift + right arrow`, `shift + down arrow`, `shift + up arrow`. 

Steps to reproduce:
* start Bitwig 1.3.9 (Mac) and APC Mini as usual
* activate `Mix Panel Layout` (Main Menu -> View -> `Mix Panel Layout`)
* create 9 tracks (of any kind) and 8 scenes of any kind
* make sure that `Session` view is active on your APC mini (active by default)
* Bitwig will render small white dots to highlight current 8x8 session (8 tracks and 8 scenes). Track 1 is now first active track. Scene 1 is now first active scene.
* On APC Mini click `shift + down arrow`. Session view moved `right`. Track 9 is now first active track. It's incorrect. It suppose to move it down (because of `down arrow`)
* On APC Mini click `shift + up arrow`. Session view moved `left`. Track 1 is now first active track. It's incorrect. It suppose to move it up (because of `up arrow`).
* Observe the same issue with `shift + left` and `shift + right` buttons. They work like `shift + down` and `shift + up` buttons.

Expected behaviour:
* Simply match standard behaviour
* `shift + down` should move 8x8 matrix down (not to the right)
* `shift + up` should move 8x8 matrix up (not to the left)
* and so on

**Comment by askaliuk** [comment]
Take a look at this code:
https://github.com/git-moss/APCmini4Bitwig/blob/master/view/SessionView.js#L23

Scenes are connected to `left` and `right` buttons.
Tracks are connected to `up` and `down` buttons.

It does not make any sense in `Mix Panel Layout`, because in this layout scenes are rows (should be navigated via `up/down`) and tracks are columns (should be navigated by `left` and `right`).

Hopefully it makes sense.

**Comment by git-moss** [comment]
Thanks for the detailed report. Please checkout the latest checkin. I also fixed some lighting issues.

**Comment by askaliuk** [comment]
Amazing. Thank you.
